spring:
  application:
    name: eureka

server:
  port: 8763

eureka:
  instance:
    hostname: eureka3
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/